### ISSUE TITLE
ImportError: cannot import name 'soft_unicode' from 'markupsafe'

### ISSUE THREAD

**Issue by akaWolf** [maximdanilchenko/aiohttp-apispec#122]
Hello.

Using jinja2 version is too old, since markupsafe changed his API.

See:
```
>>> from aiohttp_apispec import setup_aiohttp_apispec
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mnt/c/Users/akaWolf/venv/lib/python3.8/site-packages/aiohttp_apispec/__init__.py", line 1, in <module>
    from .aiohttp_apispec import AiohttpApiSpec, setup_aiohttp_apispec
  File "/mnt/c/Users/akaWolf/venv/lib/python3.8/site-packages/aiohttp_apispec/aiohttp_apispec.py", line 11, in <module>
    from jinja2 import Template
  File "/mnt/c/Users/akaWolf/venv/lib/python3.8/site-packages/jinja2/__init__.py", line 12, in <module>
    from .environment import Environment
  File "/mnt/c/Users/akaWolf/venv/lib/python3.8/site-packages/jinja2/environment.py", line 25, in <module>
    from .defaults import BLOCK_END_STRING
  File "/mnt/c/Users/akaWolf/venv/lib/python3.8/site-packages/jinja2/defaults.py", line 3, in <module>
    from .filters import FILTERS as DEFAULT_FILTERS  # noqa: F401
  File "/mnt/c/Users/akaWolf/venv/lib/python3.8/site-packages/jinja2/filters.py", line 13, in <module>
    from markupsafe import soft_unicode
ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/mnt/c/Users/akaWolf/venv/lib/python3.8/site-packages/markupsafe/__init__.py)
```

**Comment by menezesfelipee** [comment]
Install MarkupSafe 2.0.1.
Partial solution...

**Comment by akaWolf** [comment]
> Install MarkupSafe 2.0.1. Partial solution...

right, but as a workaround only

**Comment by Hazzari** [comment]
need up version jinja2>=3.0.3

**Comment by chey** [comment]
> need up version jinja2>=3.0.3

It looks like the `requirements.txt` has already been updated. Once a new release is pushed out it should be good.
