### ISSUE TITLE
date is not JSON serializable when using 

### ISSUE THREAD

**Issue by thanosexcite** [maximdanilchenko/aiohttp-apispec#47]
Hi there. Using the example from this repo's README and adding a Date field in the schema with a validator using a date as range min value, I'm getting the following exception when loading the swagger UI page:

```
Failed to load API definition.
Errors
Fetch error
Internal Server Error /api/docs/swagger.json
```

From app logs:
```py
# python bug.py 
======== Running on http://0.0.0.0:8081 ========
(Press CTRL+C to quit)
Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/usr/local/lib/python3.6/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.6/site-packages/aiohttp_apispec/aiohttp_apispec.py", line 57, in swagger_handler
    return web.json_response(request.app["swagger_dict"])
  File "/usr/local/lib/python3.6/site-packages/aiohttp/web_response.py", line 715, in json_response
    text = dumps(data)
  File "/usr/local/lib/python3.6/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'date' is not JSON serializable
```

bug.py source:
```py
from aiohttp_apispec import (
    docs,
    request_schema,
    setup_aiohttp_apispec,
)
from aiohttp import web
from marshmallow import Schema, fields, validate
from datetime import date


class RequestSchema(Schema):
    id = fields.Int()
    name = fields.Str(description="name")
    my_date = fields.Date(validate=validate.Range(min=date.today()))

@docs(
    tags=["mytag"],
    summary="Test method summary",
    description="Test method description",
)
@request_schema(RequestSchema(strict=True))
async def index(request):
    return web.json_response({"msg": "done", "data": {}})


app = web.Application()
app.router.add_post("/v1/test", index)

# init docs with all parameters, usual for ApiSpec
setup_aiohttp_apispec(
    app=app,
    title="My Documentation",
    version="v1",
    url="/api/docs/swagger.json",
    swagger_path="/api/docs",
)

# Now we can find spec on 'http://localhost:8080/api/docs/swagger.json'
# and docs on 'http://localhost:8080/api/docs'
web.run_app(app, port=8081)
```

If I replace the validation min value with something else other than a date object, The swagger UI page works fine.

BTW your package is awesome, thank you :bowing_man:

**Comment by thanosexcite** [comment]
I used a custom function to do the validation instead of using `validate.Range()`. Please close if you think that there is nothing to fix.

**Comment by maximdanilchenko** [comment]
@thanosexcite We can solve this problem with replacing std json encoder with something having support of date/datetime objects converting. For example - [`simplejson`](https://github.com/simplejson/simplejson). So I will not close this issue for now.

**Comment by maximdanilchenko** [comment]
I found this [answer](https://github.com/simplejson/simplejson/issues/86#issuecomment-34937085) interesting. Im agree with it. Also solution with custom validator is good so I will close issue.
