### ISSUE TITLE
500 internal error if no data in json

### ISSUE THREAD

**Issue by kodkuce** [maximdanilchenko/aiohttp-apispec#48]
if i send non json it just responds proper with missing fields
if i send legit it works normal
```
POST http://localhost:8080/reg HTTP/1.1
content-type: application/json

{
    "msg":"hello",
    "data":
    {
        "uName":    "nekinalog",
        "uPass":    "myhardpass",
        "uEmail":   "mail@mail.com"
    }
}
```

but if i send json that has no "data" it crashes
```
POST http://localhost:8080/reg HTTP/1.1
content-type: application/json

{
    "uName":    "nekinalog",
    "uPass":    "myhardpass",
    "uEmail":   "mail@mail.com"
}
```

```
 python3 authserver.py 
======== Running on http://0.0.0.0:8080 ========
(Press CTRL+C to quit)
Error handling request
Traceback (most recent call last):
  File "/home/me/.local/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/home/me/.local/lib/python3.7/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/home/me/.local/lib/python3.7/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/home/me/.local/lib/python3.7/site-packages/aiohttp_apispec/middlewares.py", line 40, in validation_middleware
    request[request.app["_apispec_request_data_name"]] = kwargs
  File "/home/me/.local/lib/python3.7/site-packages/aiohttp/web_app.py", line 160, in __getitem__
    return self._state[key]
KeyError: '_apispec_request_data_name'
```

Hmm is this normal behavior or am i doing something wrong?
Here my simple server api

```python
from aiohttp_apispec import (
    docs,
    request_schema,
    setup_aiohttp_apispec,
)
from marshmallow import Schema, fields
from aiohttp_apispec import validation_middleware


class ReqRequestSchema(Schema):
    uName = fields.Str(required=True)
    uPass = fields.Str(required=True)
    uEmail = fields.Str(required=True)

ROUTES = web.RouteTableDef()

@ROUTES.post('/reg')
@request_schema(ReqRequestSchema(strict=True))
async def try_reg(request):
  try:   #probbaly can ignore all stuff inhere cuz it crashes in validation_midleware 
    data = await request.json() #before this even runs, anyway will change this after
    print(data)
    txt = data['uName']
  except json.decoder.JSONDecodeError as json_error:
    return web.json_response({'error':'recived json is bad'})
  return web.Response(text=txt)


APP = web.Application(middlewares=[validation_middleware]) #error_middleware, 
APP.add_routes(ROUTES)
web.run_app(APP)
```

**Comment by maximdanilchenko** [comment]
Hi, @kodkuce!
To make `validation_middleware` work you should setup your app with `setup_aiohttp_apispec` function before running your server:
```python
setup_aiohttp_apispec(app)
```
After that you can change your code to:
```python
@routes.post('/reg')
@request_schema(ReqRequestSchema(strict=True))
async def try_reg(request):
    data = request['data']  # request data is already validated and loaded into Request object
    txt = data['uName']
    return web.Response(text=txt)
```

To catch json decode errors add your own middleware just before `validation_middleware`. Smth like:
```python
@web.middleware
async def intercept_error(request, handler):
    try:
        return await handler(request)
    except json.decoder.JSONDecodeError:
        return web.json_response({'error':'recived json is bad'}, status=400)
```
And in your app factory it can look like this:
```python
app.middlewares.extend([intercept_error, validation_middleware, authorization, database_init, e.t.c.])
```

**Comment by kodkuce** [comment]
Ty for response i got it working, main issue was i somhow missed that setup_aiohttp_apispec(app) :)
