### ISSUE TITLE
Example in README has outdated code

### ISSUE THREAD

**Issue by sad-boy-uoa** [maximdanilchenko/aiohttp-apispec#67]
Hi all,

Thank you for this fantastic library, it will be very useful for me!

I was experimenting with this library for a project of mine and noticed that the README has an out of date usage of marshmallow.Schema where the strict=True argument is passed.

In marshmallow > 3 there was a breaking change introduced as per the changelog: https://marshmallow.readthedocs.io/en/stable/changelog.html?highlight=strict#b7-2018-02-03

I'm happy to put up a PR to update the README if you need!

**Comment by thijstriemstra** [comment]
had the same issue

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/foo/__main__.py", line 6, in <module>
    from boatlife.main import main
  File "/foo/main.py", line 41, in <module>
    @request_schema(RequestSchema(strict=True))
TypeError: __init__() got an unexpected keyword argument 'strict'
```

**Comment by sad-boy-uoa** [comment]
Hi there, is there any update on this?

**Comment by maximdanilchenko** [comment]
Hi! Yes, it would be cool to include a list of difference between marshmallow < 3 and marshmallow >= 3 into documentation (and I know that many people still use 2.x versions). @sad-boy-uoa you are welcome to put up a PR. I will appreciate it:)
